//------------------------------------------------------------------------
// Copyright(c) 2023 Deadline Entertainment.
//------------------------------------------------------------------------

#ifndef VSTVERSION_H
#define VSTVERSION_H

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Metro Gaya System Player Instrument.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Metro Gaya System Player Instrument VST3 (64Bit)"
#else
#define stringFileDescription	"Metro Gaya System Player Instrument VST3"
#endif
#define stringCompanyName		"Deadline Entertainment\0"
#define stringLegalCopyright	"Copyright(c) 2023 Deadline Entertainment."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"

#endif // VSTVERSION_H