#ifndef DEADLINE_AUDIO_ENGINE_REGISTER_TYPES_H
#define DEADLINE_AUDIO_ENGINE_REGISTER_TYPES_H
#include "modules/register_module_types.h"

void initialize_deadline_audio_engine_module(ModuleInitializationLevel p_level);
void uninitialize_deadline_audio_engine_module(ModuleInitializationLevel p_level);

#endif // DEADLINE_AUDIO_ENGINE_REGISTER_TYPES_H
